# Generated by Django 2.2.3 on 2019-07-26 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='sessionDateTime',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
