# Generated by Django 2.2.3 on 2019-08-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_startpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='startPage',
            field=models.TextField(blank=True, max_length=9000, null=True),
        ),
    ]
