# Generated by Django 2.2.3 on 2019-09-01 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190822_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='visibility',
            field=models.CharField(blank=True, default='public', max_length=50, null=True),
        ),
    ]
