# Generated by Django 2.2.3 on 2019-09-01 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_customuser_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='volume',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.7, max_digits=5, null=True),
        ),
    ]
